# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab397bdc8d2eede80ef827f2e7408a7194f7e3c7f2f19416f80c926020698a064c6b58505563df2a627fd84d191831bb22e0252863d8fd04cfe3189de8cf5769

test:
  secret_key_base: 36587591e7e23e2b06261f330dab134ad14391ec41bfb919014f0637aaa2316e066f479d10baca4777aa3817177d3f5689597f460e847656b86996c92d7efd98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
